apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.rollout.name }}
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  replicas: {{ .Values.rollout.replicas }}
  revisionHistoryLimit: {{ .Values.rollout.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: rollout-canary ###
  template:
    metadata:
      labels:
        app: rollout-canary ####
    spec:
      containers:
      - name: rollouts-demo
        image: {{ .Values.rollout.image }}
        imagePullPolicy: {{ .Values.rollout.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.rollout.containerPort }}
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: {{ include "rollout-test-helm.fullname" . }}       # required
            routes:
            - primary                 # optional if there is a single route in VirtualService, required otherwise
          destinationRule:
            name: {{ include "rollout-test-helm.fullname" . }}    # required
            canarySubsetName: canary  # required
            stableSubsetName: stable # required
          
      steps:
      - setWeight: 5
      - pause:
          duration: 2m
      - setWeight: 10
      - pause:
          duration: {} # puase indefinitely 수동 promote 해야 최종 배포됨
      
      - setWeight: 20
      - pause: { duration: 31s }

