{{- if .Values.rolloutBlueGreen.active.enabled }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.rollout.activeService }}
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: {{ .Values.rolloutBlueGreen.active.type }}
  selector:
    app: rollout-bluegreen
  ports:
  - protocol: TCP
    port: {{ .Values.rolloutBlueGreen.active.port }}
    targetPort: {{ .Values.rolloutBlueGreen.active.targetPort }}
    nodePort: {{ .Values.rolloutBlueGreen.active.nodePort }}

{{- end }}

{{- if .Values.rolloutBlueGreen.preview.enabled }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.rollout.previewService }}
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: {{ .Values.rolloutBlueGreen.preview.type }}
  selector:
    app: rollout-bluegreen
  ports:
  - protocol: TCP
    port: {{ .Values.rolloutBlueGreen.preview.port }}
    targetPort: {{ .Values.rolloutBlueGreen.preview.targetPort }}
    nodePort: {{ .Values.rolloutBlueGreen.preview.nodePort }}

{{- end }}


# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "rollout-test-helm.fullname" . }}
#   labels:
#     {{- include "scp-center-api.labels" . | nindent 4 }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
#     {{- include "scp-center-api.selectorLabels" . | nindent 4 }} ### 확인하기
