# Default values for rollout-test-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
source:
  repoURL: https://github.com/gracepark0120/argorollout-test


spec:
  destination:
    namespace: rollout-test2
    server: https://kubernetes.default.svc.cluster.local

rollout:
  name: rollout-bluegreen
  replicas: 2
  revisionHistoryLimit: 2
  image: argoproj/rollouts-demo:blue
  imagePullPolicy: Always
  containerPort: 8080
  activeService: rollout-bluegreen-active
  previewService: rollout-bluegreen-preview
  autoPromotionEnabled: false


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

syncPolicy:
  automated:
    prune: false
    selfHeal: true

rolloutBlueGreen:
  active:
    enabled: true
    type: NodePort
    port: 80
    targetPort: 8080
    nodePort: 30081
  preview:
    enabled: true
    type: NodePort
    port: 80
    targetPort: 8080
    nodePort: 30082


ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
